title: LAMIR 2024
preposition: ''
description: >-
  Join us for the 1st Latin American Music Information Retrieval (LAMIR) workshop, from December 9 to 11, 2024, in Rio de Janeiro.

baseurl: "" # the subpath of your site, e.g. /blog
url: "https://lamir-workshop.github.io" # the base hostname & protocol for your site, e.g. https://example.com

# Build settings
markdown: kramdown
sass:
  style: compressed

# Exclude from processing
exclude:
  - .github/
  - venv/
  - README.md
  - LICENSE.md
  - REDISTRIBUTED.md
  - screenshot.png
  - jekyll-theme-conference.gemspec
  - purgecss.config.js
  - _config.example.yml

# Collections and their defaults
collections:
  talks:
    output: true
    permalink: /:collection/:title/
  speakers:
    output: true
    permalink: /:collection/:title/
  rooms:
    output: true
    permalink: /:collection/:title/

defaults:
  - scope:
      path: ""
      type: talks
    values:
      layout: talk
  - scope:
      path: ""
      type: speakers
    values:
      layout: speaker
  - scope:
      path: ""
      type: rooms
    values:
      layout: room

# Theme default values
conference:
  lang: en
  show_errors: True

  talks:
    main_categories:
      - name: Keynote
        color: info
      - name: Industry
        color: info
      - name: Social
        color: success
      - name: Other
        color: dark
      - name: Code
        color: primary

  link_preview:
    disable: false

  speakers:
    show_firstname: true

  location:
    url: '/location'
    map:
      home_coord: -22.86385423937762, -43.23098525405934
      map_provider: "OpenStreetMap.Mapnik"
      default_zoom: 17

  program:
    url: '/program'
    time_steps: 15
    show_alltimes: true

  navigation:
    footer:
      img: 'artista-guitarra.png'
    logo:
      name: LAMIR
      # img: 'lamir-white.png'
      img: 'fundos-no-bg.png'
      url: '/'
    links:
      - name: Author Information
        menu:
          - name: Call for Papers
            relative_url: /call4papers/
          - name: Poster Guidelines
            relative_url: /poster_guidelines/
      - name: Program
        menu:
          - name: Overview
            relative_url: /program/
          - name: Talks
            relative_url: /talks/
          - name: Poster Sessions
            relative_url: /poster_session/
          - name: Speakers
            relative_url: /speakers/
      - name: Attend
        menu:
        - name: Registration
          relative_url: /registration/
        - name: Location
          relative_url: /location/
        - name: Travel Awards
          relative_url: /travel_awards/
      - name: About
        menu:
        - name: Organizing Committee
          relative_url: /committee/
        - name: Code of Conduct
          relative_url: /coc/
        - name: Sponsors
          relative_url: /sponsors/

  info_bars:
    - title: Proceedings now available!
      color: info
      main_only: true
      text: The workshop proceedings are now available on <a href="https://zenodo.org/records/14908040"><b>Zenodo</b></a>.
    - title: Join us on Slack
      color: secondary
      main_only: true
      text: Slack will be our main platform for staying connected both during and after the workshop.
            Join using the link <b><a href="https://join.slack.com/t/lamirworkshop/shared_invite/zt-2w6w045nk-Nh4Gce13SW4tA7TaV27KfA">here</a></b>! |


  sponsors:
    sponsors:
      - name: CAPES
        full_name: Coordenação de Aperfeiçoamento de Pessoal de Nível Superior
        logo: capes.png
        url: https://www.gov.br/capes/pt-br
      - name: Google
        full_name: Google
        logo: google.png
        url: https://www.google.com
      - name: ISMIR
        full_name: International Society for Music Information Retrieval
        logo: ismir.png
        url: https://ismir.net
      - name: KHIPU
        full_name: KHIPU
        logo: khipu.png
        url: https://khipu.ai
      - name: Music AI
        logo: musicai.png
        url: https://music.ai/
    institutional_support:
      - name: IEEE SPS
        full_name: IEEE Signal Processing Society
        logo: ieee_sps.png
        url:  https://signalprocessingsociety.org
      - name: JKU
        full_name: Johannes Kepler University Linz
        logo: jku.png
        url: https://www.jku.at
      - name: NYU
        full_name: New York University
        logo: nyu.png
        url: https://www.nyu.edu
      - name: UdelaR
        full_name: Universidad de la República Uruguay
        logo: udelar.png
        url: https://udelar.edu.uy/portal/
      - name: UPF
        full_name: Universitat Pompeu Fabra
        logo: upf.png
        url:  https://www.upf.edu
      - name: UFRJ
        full_name: Universidade Federal do Rio de Janeiro
        logo: ufrj.png
        url: https://ufrj.br
