title: LAMIR 2024
preposition: ''
description: >-
  Join us for the 1st Latin American Music Information Retrieval (LAMIR) workshop, from December 9 to 11, 2024, in Rio de Janeiro.

baseurl: "" # the subpath of your site, e.g. /blog
url: "https://example.com" # the base hostname & protocol for your site, e.g. https://example.com

# Build settings
markdown: kramdown
sass:
  style: compressed

# Exclude from processing
exclude:
  - .github/
  - venv/
  - README.md
  - LICENSE.md
  - REDISTRIBUTED.md
  - screenshot.png
  - jekyll-theme-conference.gemspec
  - purgecss.config.js
  - _config.example.yml

# Collections and their defaults
collections:
  talks:
    output: true
    permalink: /:collection/:title/
  speakers:
    output: true
    permalink: /:collection/:title/
  rooms:
    output: true
    permalink: /:collection/:title/

defaults:
  - scope:
      path: ""
      type: talks
    values:
      layout: talk
  - scope:
      path: ""
      type: speakers
    values:
      layout: speaker
  - scope:
      path: ""
      type: rooms
    values:
      layout: room

# Theme default values
conference:
  lang: en
  show_errors: True

  talks:
    main_categories:
      - name: category 1
        color: info
      - name: category 2
        color: success

  link_preview:
    disable: false

  speakers:
    show_firstname: true

  location:
    url: '/location'
    map:
      home_coord: -22.85833, -43.23047
      map_provider: "OpenStreetMap.Mapnik"
      default_zoom: 17

  program:
    url: '/program'
    time_steps: 15
    show_alltimes: true

  navigation:
    footer:
      img: 'artista-guitarra.png'
    logo:
      name: LAMIR
      # img: 'lamir-white.png'
      img: 'fundos-no-bg.png'
      url: '/'
    links:
      - name: Call for Papers
        relative_url: /call4papers/
      - name: Registration
        relative_url: /registration/
      - name: Program
        relative_url: /program/
      # - live: true
      # - name: Speakers
      #   relative_url: /speakers/
      - name: Location
        relative_url: /location/
      # - name: Travel Awards
      #   relative_url: /travel_awards/
      - name: Sponsors
        relative_url: /sponsors/
      - name: Committee
        relative_url: /committee/
      # - name: Code of Conduct
      #   relative_url: /coc/

  # info_bars:
  #   - title:
  #     color: info
  #     main_only: false
  #     text:
  sponsors:
    sponsors:
      - name: CAPES
        full_name: Coordenação de Aperfeiçoamento de Pessoal de Nível Superior
        logo: capes.png
        url: https://www.gov.br/capes/pt-br
      - name: Google
        full_name: Google
        logo: google.png
        url: https://www.google.com
      - name: ISMIR
        full_name: International Society for Music Information Retrieval
        logo: ismir.png
        url: https://ismir.net
      - name: KHIPU
        full_name: KHIPU
        logo: khipu.png
        url: https://khipu.ai
      - name: Music AI
        logo: musicai.png
        url: https://music.ai/
    institutional_support:
      - name: IEEE SPS
        full_name: IEEE Signal Processing Society
        logo: ieee_sps.png
        url:  https://signalprocessingsociety.org
      - name: JKU
        full_name: Johannes Kepler University Linz
        logo: jku.png
        url: https://www.jku.at
      - name: NYU
        full_name: New York University
        logo: nyu.png
        url: https://www.nyu.edu
      - name: UdelaR
        full_name: Universidad de la República Uruguay
        logo: udelar.png
        url: https://udelar.edu.uy/portal/
      - name: UPF
        full_name: Universitat Pompeu Fabra
        logo: upf.png
        url:  https://www.upf.edu
      - name: UFRJ
        full_name: Universidade Federal do Rio de Janeiro
        logo: ufrj.png
        url: https://ufrj.br
